// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvALbXmvThrwMnS50WUeB_qDBGT7doBTg',
    appId: '1:682497354056:web:9ec221da7ee1ce7cc6ab7d',
    messagingSenderId: '682497354056',
    projectId: 'viru-6fc64',
    authDomain: 'viru-6fc64.firebaseapp.com',
    storageBucket: 'viru-6fc64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAStHG76wUd5SJp0GxFFBVro9JLxdqG5ak',
    appId: '1:682497354056:android:d5722c7e3e6811fac6ab7d',
    messagingSenderId: '682497354056',
    projectId: 'viru-6fc64',
    storageBucket: 'viru-6fc64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrd_2j2gzY_CcxwJ481iIRun9Me96hLw',
    appId: '1:682497354056:ios:af77836a560c7db8c6ab7d',
    messagingSenderId: '682497354056',
    projectId: 'viru-6fc64',
    storageBucket: 'viru-6fc64.appspot.com',
    iosClientId: '682497354056-ij2al73o328t9agud0dn9sg3resdmvnm.apps.googleusercontent.com',
    iosBundleId: 'com.viru.indal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrd_2j2gzY_CcxwJ481iIRun9Me96hLw',
    appId: '1:682497354056:ios:af77836a560c7db8c6ab7d',
    messagingSenderId: '682497354056',
    projectId: 'viru-6fc64',
    storageBucket: 'viru-6fc64.appspot.com',
    iosClientId: '682497354056-ij2al73o328t9agud0dn9sg3resdmvnm.apps.googleusercontent.com',
    iosBundleId: 'com.viru.indal',
  );
}
